# Generated by Django 5.1.6 on 2025-03-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_remove_servicio_nombre_servicio_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='posicion',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
