# Generated by Django 5.1.6 on 2025-03-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_orden_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='posicion',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
