# Generated by Django 5.1.6 on 2025-03-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_orden_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeninventario',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
