# Generated by Django 5.1.6 on 2025-03-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_ordeninventario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='cantidad',
            field=models.CharField(default='', max_length=50),
        ),
    ]
