# Generated by Django 5.1.6 on 2025-03-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0011_cliente_motor_orden_cliente_registrado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motor",
            name="especificaciones",
        ),
        migrations.AddField(
            model_name="motor",
            name="altura_cabeza",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Altura de la cabeza",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motor",
            name="angulo_asiento",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Ángulo de asiento",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motor",
            name="carrera",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Carrera"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motor",
            name="diametro_alojamiento",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Diámetro de alojamiento",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motor",
            name="diametro_cabeza_admision",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Diámetro de cabeza (admisión)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motor",
            name="diametro_cabeza_escape",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Diámetro de cabeza (escape)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motor",
            name="diametro_cilindro",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Diámetro de cilindros",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motor",
            name="diametro_munon_bancada",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Diámetro de muñón de bancada",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motor",
            name="diametro_munon_biela",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Diámetro de muñón de biela",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motor",
            name="diametro_piston",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Diámetro del pistón",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motor",
            name="diametro_vastago",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Diámetro del vástago",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motor",
            name="distancia_valvula",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distancia válvula",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="motor",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
