# Generated by Django 5.1.6 on 2025-03-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_remove_motor_especificaciones_motor_altura_cabeza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='angulo_asiento',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='diametro_vastago',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='distancia_valvula',
        ),
        migrations.AddField(
            model_name='motor',
            name='angulo_asiento_admision',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ángulo de asiento (admisión)'),
        ),
        migrations.AddField(
            model_name='motor',
            name='angulo_asiento_escape',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ángulo de asiento (escape)'),
        ),
        migrations.AddField(
            model_name='motor',
            name='diametro_vastago_admision',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diámetro vástago (admisión)'),
        ),
        migrations.AddField(
            model_name='motor',
            name='diametro_vastago_escape',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diámetro vástago (escape)'),
        ),
        migrations.AddField(
            model_name='motor',
            name='distancia_valvula_admision',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Distancia válvula (admisión)'),
        ),
        migrations.AddField(
            model_name='motor',
            name='distancia_valvula_escape',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Distancia válvula (escape)'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='altura_cabeza',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Altura de la cabeza'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='carrera',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='diametro_alojamiento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diámetro de alojamiento'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='diametro_cabeza_admision',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diámetro de cabeza (admisión)'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='diametro_cabeza_escape',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diámetro de cabeza (escape)'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='diametro_cilindro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diámetro de cilindros'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='diametro_munon_bancada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diámetro de muñón de bancada'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='diametro_munon_biela',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diámetro de muñón de biela'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='diametro_piston',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diámetro del pistón'),
        ),
    ]
