# Generated by Django 5.1.6 on 2025-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0014_alter_motor_altura_cabeza_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="orden_imagenes/",
                verbose_name="Imagen Adjunta",
            ),
        ),
    ]
