# Generated by Django 5.1.6 on 2025-04-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0016_remove_orden_imagen_ordenimagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden",
            name="fecha_aceptacion",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que la orden fue aceptada.",
                null=True,
                verbose_name="Fecha de Aceptación",
            ),
        ),
        migrations.AddField(
            model_name="orden",
            name="fecha_entrega",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que la orden fue marcada como entregada.",
                null=True,
                verbose_name="Fecha de Entrega",
            ),
        ),
        migrations.AddField(
            model_name="orden",
            name="fecha_terminacion",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que todos los servicios de la orden se completaron (estado LISTO).",
                null=True,
                verbose_name="Fecha de Terminación",
            ),
        ),
    ]
