# Generated by Django 5.1.6 on 2025-05-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0017_orden_fecha_aceptacion_orden_fecha_entrega_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="fecha_fin",
            field=models.DateTimeField(
                blank=True,
                help_text="Marca de tiempo cuando el servicio pasa a 'Terminado'.",
                null=True,
                verbose_name="Fecha Fin Servicio",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="fecha_inicio",
            field=models.DateTimeField(
                blank=True,
                help_text="Marca de tiempo cuando el servicio pasa a 'En proceso'.",
                null=True,
                verbose_name="Fecha Inicio Servicio",
            ),
        ),
    ]
