# Generated by Django 5.1.6 on 2025-05-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0018_servicio_fecha_fin_servicio_fecha_inicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="motor",
            name="num_cabezas",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Ej: 1, 2",
                null=True,
                verbose_name="Número de Cabezas",
            ),
        ),
        migrations.AddField(
            model_name="motor",
            name="num_cilindros",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Ej: 4, 6, 8",
                null=True,
                verbose_name="Número de Cilindros",
            ),
        ),
    ]
